name = "lan-planner"
compatibility_date = "2026-01-01"
pages_build_output_dir = "."

[[kv_namespaces]]
binding = "DATA_KV"
id = "c3700f7d096a4b3782f2132b1392579b"

[vars]
ACCESS_CODE = "Fadol"

[env.preview]

[[env.preview.kv_namespaces]]
binding = "DATA_KV"
id = "c3700f7d096a4b3782f2132b1392579b"

[env.preview.vars]
ACCESS_CODE = "Fadol"
